### ISSUE TITLE
hackage source tarball is missing some example_data files

### ISSUE THREAD

**Issue by divanorama** [adamConnerSax/Frames-streamly#1]
https://hackage.haskell.org/package/Frames-streamly-0.1.1.0/src/

missing example.csv and acs100k.csv from [example_data](https://github.com/adamConnerSax/Frames-streamly/tree/master/example_data)
And some examples fail because of that
https://github.com/adamConnerSax/Frames-streamly/blob/master/examples/Strictness.hs#L107
https://github.com/adamConnerSax/Frames-streamly/blob/master/examples/StrictnessPaths.hs#L12

**Comment by adamConnerSax** [comment]
Fixed by https://github.com/adamConnerSax/Frames-streamly/commit/bdd02754a35bc3dc6abc866f783f1dd8ccd8e09c

Thanks for catching this!  I fixed in the newest release and I'll deprecate the current release.  I removed the example that required those files since it was for debugging, not a real example.
